apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-{{ .Values.appname.name }}-secrets
  namespace: {{ .Values.namespace.name }}
type: Opaque
data:
  {{- range $k, $v:= .Values.configs }}
    {{ $k }}: {{ $v | b64enc }}
  {{- end }}