# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.appname.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ .Values.appname.name }}
  ports:
  - name: {{ .Values.appname.name }}
    port: 3306
  clusterIP: None

# pod-name.service-name.namespace.svc.cluster.local
# pod-name.service-name
# mysql-0.mysql.mysql.svc.cluster.local