apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.todoapp.names.todoapp_service}}
  namespace: {{ .Values.todoapp.namespace.name}}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.todoapp.names.todoappname}}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
