apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Values.todoapp.names.todoappname }}
  namespace: {{ .Values.todoapp.namespace.name }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.todoapp.rollup.maxSurge }}
      maxUnavailable: {{ .Values.todoapp.rollup.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ .Values.todoapp.names.todoapp_label }}
  template:
    metadata:
      labels:
        app: {{ .Values.todoapp.names.todoapp_label }}
    spec:
      serviceAccountName: {{ .Chart.Name }}-{{ .Values.todoapp.rbac.name }}
      containers:
      - name: {{ .Chart.Name }}-{{ .Values.todoapp.image.name }}
        image: {{ .Values.todoapp.image.repository }}:{{ .Values.todoapp.image.version }}
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: {{ .Chart.Name }}-{{ .Values.todoapp.names.app_secret }}-volume
          mountPath: "/app/secrets"
          readOnly: true
        - name: {{ .Chart.Name }}-{{ .Values.todoapp.names.app_config }}-volume
          mountPath: "/app/configs"
          readOnly: true
        resources:
          requests:
            memory: {{ .Values.todoapp.resources.requests.memory }}
            cpu:  {{ .Values.todoapp.resources.requests.cpu }}
          limits:
            memory:  {{ .Values.todoapp.resources.limits.memory }}
            cpu:  {{ .Values.todoapp.resources.limits.cpu }}
        env:
        {{- range $k, $v := .Values.todoapp.data }}
        - name: {{ $k }}
          valueFrom:
            secretKeyRef:
              name: {{ $.Chart.Name }}-{{ $.Values.todoapp.names.app_secret }}
              key: {{ $k }}
        {{- end }}
        - name: PYTHONUNBUFFERED
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-{{ .Values.todoapp.names.app_config }}
              key: PYTHONUNBUFFERED
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: api/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: api/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-{{ .Values.todoapp.names.pv_data }}
      - name: {{ .Chart.Name }}-{{ .Values.todoapp.names.app_secret }}-volume
        secret:
          secretName: {{ .Chart.Name }}-{{ .Values.todoapp.names.app_secret }}
      - name: {{ .Chart.Name }}-{{ .Values.todoapp.names.app_config }}-volume
        configMap:
          name: {{ .Chart.Name }}-{{ .Values.todoapp.names.app_config }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Values.todoapp.names.todoapp_label }}