apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-{{ .Values.todoapp.names.todoappname }}-ingress
  namespace: {{ .Values.todoapp.namespace.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /(|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Chart.Name }}-{{ .Values.todoapp.names.todoapp_service }}
            port:
              number: 80
