apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-{{ .Values.todoapp.names.pv_data }}
  namespace: {{ .Values.todoapp.namespace.name}}
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ .Values.todoapp.storage.capacity.storage }}
  hostPath:
    path: /data/
