
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-{{ .Values.todoapp.names.pv_data }}
  namespace: {{ .Values.todoapp.namespace.name }}
spec:
  volumeName: {{ .Chart.Name }}-{{ .Values.todoapp.names.pv_data }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.todoapp.storage.requests.storage }}